services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # Ports STARTTLS (sans TLS)
      - "--entrypoints.mail-smtp.address=:25"
      - "--entrypoints.mail-pop3.address=:110"
      # Ports SSL implicite (avec TLS)
      - "--entrypoints.mail-submissions.address=:465"
      - "--entrypoints.mail-pop3s.address=:995"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/acme.json"
    ports:
      - "25:25"
      - "465:465"
      - "110:110"
      - "995:995"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik/acme.json:/acme.json
    networks:
      default:
        ipv4_address: ${TRAEFIK_IP}

  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: ${MAIL_HOSTNAME}
    domainname: ${DOMAIN}
    environment:
      - SSL_TYPE=letsencrypt-pregenerated
      - SSL_CERT_PATH=/etc/letsencrypt/acme.json
      - ENABLE_POP3=1
      - ENABLE_PROXY_PROTOCOL=1
      - SMTP_ONLY=0
      - PERMIT_DOCKER=network
      - POSTFIX_MAILBOX_SIZE_LIMIT=0
      - DOVECOT_TRUSTED_NETWORKS=${TRAEFIK_IP}
      - PUBLIC_IP=${PUBLIC_IP}
      - DOMAIN=${DOMAIN}
      - DEFAULT_SMTP_ALIAS=${DEFAULT_SMTP_ALIAS}
      - CATCHALL_ALIAS=${CATCHALL_ALIAS}
      - BOUNCE_ALIAS=${BOUNCE_ALIAS}
      - DEFAULT_SMTP_PASSWORD=${DEFAULT_SMTP_PASSWORD}
      - CATCHALL_PASSWORD=${CATCHALL_PASSWORD}
      - BOUNCE_PASSWORD=${BOUNCE_PASSWORD}
    volumes:
      - ./data/dms/mail-data/:/var/mail/
      - ./data/dms/config/:/tmp/docker-mailserver/
      - ./data/traefik/acme.json:/etc/letsencrypt/acme.json:ro
    networks:
      default:
        ipv4_address: ${MAILSERVER_IP}
    labels:
      - "traefik.enable=true"
      # SMTP (25) - Sans HostSNI car STARTTLS
      - "traefik.tcp.routers.mail-smtp.entrypoints=mail-smtp"
      - "traefik.tcp.routers.mail-smtp.service=mail-smtp"
      - "traefik.tcp.services.mail-smtp.loadbalancer.server.port=25"
      - "traefik.tcp.services.mail-smtp.loadbalancer.proxyProtocol.version=2"
      
      # SMTPS (465) - Avec HostSNI et passthrough car TLS implicite
      - "traefik.tcp.routers.mail-submissions.rule=HostSNI(`${MAIL_HOSTNAME}`)"
      - "traefik.tcp.routers.mail-submissions.entrypoints=mail-submissions"
      - "traefik.tcp.routers.mail-submissions.tls.passthrough=true"
      - "traefik.tcp.services.mail-submissions.loadbalancer.server.port=465"
      - "traefik.tcp.services.mail-submissions.loadbalancer.proxyProtocol.version=2"
      
      # POP3 (110) - Sans HostSNI car STARTTLS
      - "traefik.tcp.routers.mail-pop3.entrypoints=mail-pop3"
      - "traefik.tcp.routers.mail-pop3.service=mail-pop3"
      - "traefik.tcp.services.mail-pop3.loadbalancer.server.port=110"
      - "traefik.tcp.services.mail-pop3.loadbalancer.proxyProtocol.version=2"
      
      # POP3S (995) - Avec HostSNI et passthrough car TLS implicite
      - "traefik.tcp.routers.mail-pop3s.rule=HostSNI(`${MAIL_HOSTNAME}`)"
      - "traefik.tcp.routers.mail-pop3s.entrypoints=mail-pop3s"
      - "traefik.tcp.routers.mail-pop3s.tls.passthrough=true"
      - "traefik.tcp.services.mail-pop3s.loadbalancer.server.port=995"
      - "traefik.tcp.services.mail-pop3s.loadbalancer.proxyProtocol.version=2"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: ${DOCKER_SUBNET} 